### PR TITLE
Bigger textures data than need.

### PR DESCRIPTION
**Pull request by UnrealKaraulov**
Right?

### CODE REVIEW

**Comment by UnrealKaraulov** [comment]
Also need write 256 short value before palette (something like palette size?) it requires in some cases.

**Comment by UnrealKaraulov** [comment]
I don't know, padding (4 bytes align?) is really needed ?

**Comment by UnrealKaraulov** [comment]
@wootguy this is mistake in code

**Comment by wootguy** [comment]
yes this was a mistake, should have used mipHeight there. It's only used for the aaatrigger texture so there's very little space wasted but still a good find. The padding was already there in texDataSize.

**Pull request closed without merging**
