### PR TITLE
Create test map

### PR DESCRIPTION
**Pull request by 2020karaulov2020**
Create test map with **bspguy -testnew** cmd.

### CODE REVIEW

**Comment by 2020karaulov2020** [comment]
@wootguy you don't know why first solid lost one triangle ?

![Uploading dTXnL4M[1].png…]()

**Comment by 2020karaulov2020** [comment]
I can create room with create_solid ?))

**Comment by wootguy** [comment]
What's the point of creating an empty BSP? Hammer is much better for building new maps.

> @wootguy you don't know why first solid lost one triangle ?

Not without debugging, no. My first steps would be checking the triangle count on the model, and checking if the face is inverted.

> I can create room with create_solid ?))

Sort of, but it wouldn't be optimized like a normal BSP room. It would have to be created out of convex models.

**Comment by 2020karaulov2020** [comment]
@wootguy I tried create random room generator, but create_solid can create only cube64x64x64))))

**Comment by wootguy** [comment]
Models can be edited with the Transformation widget, but that's only meant for invisible triggers. Visible solids would need to be split to prevent the "max surface extents" error, and there's no code for that yet.

I think you'd be better off creating random rooms in the [RMF format](https://web.archive.org/web/20170222045107/http://extension.ws/hlfix/rmf.html) and then compiling to BSP. Updating bspguy to do this properly would mean re-implementing all of the map compiler tools.

**Comment by 2020karaulov2020** [comment]
But if generate random map directly in bsp format, it can be used in mods etc)

@wootguy bspguy no have 'rotation' widget ? only move and scale?

**Comment by wootguy** [comment]
Why can't maps compiled from RMFs be used in mods? There shouldn't be any difference.

> bspguy no have 'rotation' widget ? only move and scale?

Right. Vertexes can be moved if you need angled faces.

**Comment by 2020karaulov2020** [comment]
> Why can't maps compiled from RMF/MAP be used in mods? There shouldn't be any difference.
> 
> > bspguy no have 'rotation' widget ? only move and scale?
> 
> Right. Vertexes can be moved if you need angled faces.
Realtime, without compilers.

**Pull request closed without merging**
