### PR TITLE
[bspguy v4 WIP] 

### PR DESCRIPTION
**Pull request by UnrealKaraulov**
**1. Export and import .bsp models.** 
 **_Description:_** You can extract a model from any map, and import it to another.
**2. Export and import .wad**
 **_Description:_** You can extract textures from the .bsp file. Or upload them back in map.
**3. Export and import .ent (entity file)**
 **_Description:_** You can extract entities to file. Edit it and import back. 
**4. Bug fixes. (Found by static analyzer, or manually)**
  **_Description:_** 
Now support latest c++/c language. (but removed 'using namespace std' and adding prefix std:: to some functions)
Replaces some functions and added new to easy access and remove useless code. 
Removed and added checks in multiple code places.
Fixed  crashes and errors.
**5. Preparing bspguy to render .mdl models in future**
**_Description:_** Added mdlviewer source code, with test file main_mdlviewer.cpp. It can be build and run, it works.

@wootguy I create new empty Pull Request because old pull request has many trash. (messages, very very big count of commits, etc)
Now you can review it and merge if all okay ?

### CODE REVIEW

**Comment by UnrealKaraulov** [comment]
@wootguy i tried to use VertexBuffer to draw models, but got random triangles ))) 
May be you can tell me how to make mdl viewer code compatible with bsp guy ?

**Comment by wootguy** [comment]
What happened to all the pull requests? I guess deleting your user deleted those too for some reason. It would have been nice to have the old stuff for context though.

Anyway, you're right about the old PR getting too cluttered, but this one will get 100+ comments as well. Please split this up into small chunks. I don't have the energy to do these huge PRs anymore.

A PR that only includes `1. Export and import .bsp models.` would be a good start.

**Comment by wootguy** [comment]
> 
> 
> @wootguy i tried to use VertexBuffer to draw models, but got random triangles )))
> May be you can tell me how to make mdl viewer code compatible with bsp guy ?

MDL meshes mix draw types a lot (e.g. GL_TRIANGLE_STRIP + GL_TRIANGLE_FAN), so isn't very easily converted to a vertex buffer. You might need to [convert those to GL_TRIANGLES first](https://github.com/wootguy/HL_Tools/commit/df7bda1b5d0deb4757a43b17f9162a4b4784724f) or something.

**Comment by UnrealKaraulov** [comment]
@wootguy My аccount was delеted due to a cоmplaint from Vаlve about illegаl content in my repositories.

@wootguy 
I don't know how to split pull request to multiple. 
The changes are highly interconnected. 

Can I delete something one ?

**Comment by UnrealKaraulov** [comment]
@wootguy for example directive 'using namespace std' cause problem with conflict std::byte and byte, you tell me in previous pull request to replace BYTE to byte, and then I got this problem, I fixed it with removing 'using namespace std' from code and adding prefix namespace 'std' to needed code.

**Comment by wootguy** [comment]
If you can get the code changes down to 1,000 lines or less then that's fine too.

**Comment by UnrealKaraulov** [comment]
I'm sorry, but I don't have enough time to deal with splitting changes and compressing the code, I think even the import export will take more than 1000 lines in different files.

at the beginning of next year I will have a lot of free time then I can do it

**Comment by UnrealKaraulov** [comment]
@wootguy 50% of changes you can just skip because it adding just std namespace prefixes. 

And you can skip mdlviewer directory because it just prepare you can exclude it from project if not needed

**Comment by UnrealKaraulov** [comment]
@wootguy You can just do test, I think all features from original bspguy will be working properly! there are not so many changes as you think!

**Comment by UnrealKaraulov** [comment]
@wootguy about mdlviewer, I move your code for convert to triangles, and it works with default program. But not works with any shader active. You can see ? https://github.com/UnrealKaraulov/bspguy/tree/bspguy_v4_WIP

**Comment by rtxa** [comment]
@UnrealKaraulov Sorry for intromising in your conversation. I think you should follow wootguy advice if you really want your pull request to be considered, and also because this will be useful for you everytime you want to submit a pull request for any project.

For me it would be infortunate that the reason your PR is not getting merged it's only because you have everything mixed.

## Reasons

1. It would be better to split this in severals pull request instead of a big one, because these changes you mentions are not necessaraly dependant from one eachother (Importing a map and import a wad are two different things).

2. It makes more easy for the repository owner to review it. He will be focusing in just one problem instead of four. It's less error prone and if there are any fixes to do, it will be clear he's doing it for that problem.

3. It will give you more clarity in your code. Instead of working in 5 problems at the same time, you will be working in just one.

Besides, you have already make a list of the changes you did, it would make more sense to do 5 pull request instead of just a big one. For example:

If one pull request depends from another one being merged first, you shoud make this clear in this way

- Pull request 1: Export and import .bsp models
- Pull request 2: Export and import .wad
   Depends on PR 1 to be merged first.

Also, you mention you don't have too much time, but all this work would be in vain if you don't make everything clear, step by step, maybe you should start to apply the splitting problems in parts from the beggining to avoid these situations in the future.

**Comment by UnrealKaraulov** [comment]
@rtxa There is no way for me to go back to any point of change since the account was deleted following a complaint from Valve. And on this reason I got one big commit!

**Comment by UnrealKaraulov** [comment]
@rtxa I has no time for split this changes, sorry... (

**Comment by rtxa** [comment]
@UnrealKaraulov There's no rush, the help is appreciated, but when it comes with PRs that are complex, well they end up in nothing if the steps are not detailed and the concerns are not splited up correctly. You also do changes that are trivial like removing the namespace or bugfixes found by static analyzer, they should have been done in differents PRs too. 
 
It's your code at the end and you know it better than us, involving us in trying to understand what you have done, in trying to split it to test it better, to see if there are any bugs or anything to fix/improve, to see if it follows the code guidelines of the rest of the project. That's a lot of time being loosed and probably it can be more easy to write it from 0.

When you have the time, try to think in how to split it up.

**Comment by UnrealKaraulov** [comment]
I'm hardly going to do, no time or desire :(

**Comment by UnrealKaraulov** [comment]
I'm hardly going to do, no time or desire :(

**Pull request closed without merging**
